"""
Sample data for live demo sessions.
Represents a realistic Series B AI/Data startup with GTM gaps.
"""

SAMPLE_ENGAGEMENT = {
    "company_name": "NeuralFlow AI",
    "contact_email": "cto@neuralflow.ai",
    "contact_name": "Alex Chen",
    "stage": "series_b",
    "arr_range": "$12M-$18M",
}

SAMPLE_GTM_DATA = {
    "company_profile": {
        "name": "NeuralFlow AI",
        "industry": "Enterprise AI/ML Platform",
        "sub_vertical": "MLOps & Model Management",
        "stage": "series_b",
        "arr": 14500000,
        "mrr": 1208333,
        "headcount": 85,
        "gtm_headcount": 22,
        "founding_year": 2022,
        "hq_location": "San Francisco, CA",
        "target_markets": ["Financial Services", "Healthcare", "Manufacturing", "Technology"],
    },
    "gtm_model": {
        "motion_type": "hybrid",
        "primary_channel": "outbound_sales",
        "secondary_channels": ["inbound_content", "partner_referrals", "events"],
        "icp_definition": {
            "company_size": "500-10000 employees",
            "industries": ["Financial Services", "Healthcare", "Manufacturing"],
            "titles": [
                "VP of Engineering",
                "Head of ML/AI",
                "CTO",
                "VP Data Science",
                "Director of MLOps",
            ],
            "budget_range": "$100K-$500K annually",
            "pain_points": [
                "Model deployment takes months",
                "No visibility into model performance in production",
                "Shadow ML experiments with no governance",
                "Compliance requirements for model auditing",
                "Fragmented tooling across ML lifecycle",
            ],
        },
        "personas": [
            {
                "title": "VP of Engineering",
                "role_in_buying": "decision_maker",
                "key_concerns": ["Team productivity", "System reliability", "Cost control"],
            },
            {
                "title": "Head of ML/AI",
                "role_in_buying": "champion",
                "key_concerns": ["Experiment tracking", "Model versioning", "Deployment speed"],
            },
            {
                "title": "CISO / Compliance",
                "role_in_buying": "influencer",
                "key_concerns": ["Model audit trails", "Data governance", "Regulatory compliance"],
            },
        ],
        "pricing_model": "usage_based_with_platform_fee",
        "avg_deal_size": 145000,
        "avg_sales_cycle_days": 78,
        "win_rate": 0.22,
        "expansion_rate": 0.15,
    },
    "sales_process": {
        "stages": [
            {
                "name": "Lead",
                "conversion_rate": 0.12,
                "avg_days_in_stage": 5,
                "activities": ["Email outreach", "LinkedIn connect", "Content download"],
            },
            {
                "name": "Qualified",
                "conversion_rate": 0.35,
                "avg_days_in_stage": 12,
                "activities": ["Discovery call", "Technical requirements gathering"],
            },
            {
                "name": "Demo/POC",
                "conversion_rate": 0.45,
                "avg_days_in_stage": 21,
                "activities": ["Product demo", "POC setup", "Technical deep dive"],
            },
            {
                "name": "Proposal",
                "conversion_rate": 0.55,
                "avg_days_in_stage": 18,
                "activities": ["Proposal creation", "Pricing negotiation", "Legal review"],
            },
            {
                "name": "Negotiation",
                "conversion_rate": 0.65,
                "avg_days_in_stage": 15,
                "activities": ["Contract review", "Security questionnaire", "Procurement"],
            },
            {
                "name": "Closed Won",
                "conversion_rate": 1.0,
                "avg_days_in_stage": 0,
                "activities": ["Signing", "Onboarding kickoff"],
            },
        ],
        "lead_sources": [
            {"source": "Outbound SDR", "volume_monthly": 180, "conversion_rate": 0.08, "cac": 28000},
            {"source": "Inbound Content", "volume_monthly": 320, "conversion_rate": 0.04, "cac": 15000},
            {"source": "Partner Referrals", "volume_monthly": 25, "conversion_rate": 0.18, "cac": 22000},
            {"source": "Events/Conferences", "volume_monthly": 45, "conversion_rate": 0.06, "cac": 35000},
            {"source": "Product-Led (Freemium)", "volume_monthly": 90, "conversion_rate": 0.02, "cac": 8000},
        ],
        "bottlenecks": [
            "POC stage takes too long — average 21 days for what should be 7-10 days",
            "SDR-to-AE handoff loses context; discovery gets repeated",
            "No standardized demo environment — each demo is custom",
            "Legal/security review bottleneck adds 2-3 weeks",
            "Founder still involved in 60% of deals over $200K",
        ],
        "automation_level": "basic",
    },
    "competitive_landscape": {
        "direct_competitors": [
            {
                "name": "MLflow (Databricks)",
                "positioning": "Open-source ML lifecycle management",
                "strengths": ["Brand recognition", "Databricks ecosystem", "Open-source community"],
                "weaknesses": ["Complex setup", "Limited governance", "Requires Databricks for full value"],
            },
            {
                "name": "Weights & Biases",
                "positioning": "ML experiment tracking and model management",
                "strengths": ["Developer experience", "Community", "Visualization"],
                "weaknesses": ["Limited deployment features", "Pricing at scale", "No compliance features"],
            },
            {
                "name": "Seldon",
                "positioning": "ML deployment and monitoring",
                "strengths": ["Kubernetes-native", "Model serving", "A/B testing"],
                "weaknesses": ["Narrow focus on deployment", "Complex operations", "Limited experiment tracking"],
            },
        ],
        "differentiation": [
            "Unified platform covering full ML lifecycle (experiment → production → governance)",
            "Built-in compliance and audit trail features for regulated industries",
            "AI-powered anomaly detection for model drift and performance degradation",
            "Fastest time-to-deployment in the market (under 24 hours for standard models)",
        ],
        "moat_assessment": "Moderate — strong product differentiation in governance/compliance, but core MLOps features increasingly commoditized. Network effects limited. Data moat building through cross-customer performance benchmarks.",
    },
}

SAMPLE_SALES_DATA = {
    "pipeline": {
        "total_pipeline_value": 8200000,
        "weighted_pipeline": 3100000,
        "pipeline_coverage_ratio": 2.1,
        "stages": [
            {"name": "Lead", "deal_count": 142, "total_value": 2800000, "avg_age_days": 8, "conversion_to_next": 0.12},
            {"name": "Qualified", "deal_count": 38, "total_value": 1900000, "avg_age_days": 15, "conversion_to_next": 0.35},
            {"name": "Demo/POC", "deal_count": 18, "total_value": 1650000, "avg_age_days": 24, "conversion_to_next": 0.45},
            {"name": "Proposal", "deal_count": 9, "total_value": 1100000, "avg_age_days": 20, "conversion_to_next": 0.55},
            {"name": "Negotiation", "deal_count": 5, "total_value": 750000, "avg_age_days": 18, "conversion_to_next": 0.65},
        ],
    },
    "velocity_metrics": {
        "avg_deal_velocity_days": 78,
        "time_to_first_value_days": 45,
        "monthly_meetings_booked": 42,
        "meeting_to_opp_rate": 0.28,
        "demo_to_close_rate": 0.22,
        "response_time_hours": 4.2,
    },
    "rep_performance": [
        {"rep_id": "AE-001", "quota": 600000, "attainment_pct": 0.85, "deals_closed": 4, "avg_deal_size": 128000, "win_rate": 0.28, "activities_per_day": 18},
        {"rep_id": "AE-002", "quota": 600000, "attainment_pct": 0.62, "deals_closed": 3, "avg_deal_size": 124000, "win_rate": 0.19, "activities_per_day": 12},
        {"rep_id": "AE-003", "quota": 600000, "attainment_pct": 1.10, "deals_closed": 5, "avg_deal_size": 132000, "win_rate": 0.31, "activities_per_day": 22},
        {"rep_id": "SDR-001", "quota": 0, "attainment_pct": 0, "deals_closed": 0, "avg_deal_size": 0, "win_rate": 0, "activities_per_day": 65},
        {"rep_id": "SDR-002", "quota": 0, "attainment_pct": 0, "deals_closed": 0, "avg_deal_size": 0, "win_rate": 0, "activities_per_day": 48},
    ],
    "cohort_metrics": {
        "nrr_pct": 108,
        "gross_churn_pct": 12,
        "expansion_revenue_pct": 20,
        "logo_retention_pct": 88,
        "avg_contract_length_months": 14,
    },
}

SAMPLE_FINANCIALS = {
    "unit_economics": {
        "cac": 24500,
        "cac_blended": 24500,
        "cac_sales_led": 32000,
        "cac_product_led": 9500,
        "ltv": 185000,
        "ltv_cac_ratio": 7.5,
        "payback_months": 22,
        "gross_margin_pct": 68,
        "contribution_margin_pct": 42,
        "magic_number": 0.58,
        "burn_multiple": 2.4,
    },
    "revenue_breakdown": {
        "new_arr": 5200000,
        "expansion_arr": 2900000,
        "churned_arr": 1740000,
        "net_new_arr": 6360000,
        "services_revenue": 850000,
    },
    "cost_structure": {
        "total_gtm_spend": 4200000,
        "sales_comp": 2100000,
        "marketing_spend": 1400000,
        "tool_subscriptions": 380000,
        "hosting_ai_costs": 1200000,
        "total_cogs": 4640000,
        "gross_margin_dollars": 9860000,
    },
    "ai_specific_costs": {
        "llm_api_monthly": 18000,
        "ai_tool_subscriptions_monthly": 12500,
        "ai_headcount_costs_monthly": 0,
        "total_ai_spend_monthly": 30500,
        "ai_spend_as_pct_revenue": 2.5,
    },
}

SAMPLE_TOOLS = {
    "tools": [
        {
            "name": "Salesforce",
            "category": "crm",
            "vendor": "Salesforce",
            "monthly_cost": 4800,
            "annual_cost": 57600,
            "users": 22,
            "utilization_pct": 55,
            "integrations": ["HubSpot", "Outreach"],
            "satisfaction_score": 5,
            "data_flows": [
                {"direction": "bidirectional", "connected_tool": "HubSpot", "data_type": "contacts", "automation_level": "basic"},
                {"direction": "outbound", "connected_tool": "Outreach", "data_type": "accounts", "automation_level": "manual"},
            ],
        },
        {
            "name": "HubSpot Marketing",
            "category": "marketing_automation",
            "vendor": "HubSpot",
            "monthly_cost": 3200,
            "annual_cost": 38400,
            "users": 8,
            "utilization_pct": 40,
            "integrations": ["Salesforce"],
            "satisfaction_score": 6,
            "data_flows": [
                {"direction": "bidirectional", "connected_tool": "Salesforce", "data_type": "leads", "automation_level": "basic"},
            ],
        },
        {
            "name": "Outreach",
            "category": "sales_engagement",
            "vendor": "Outreach",
            "monthly_cost": 2400,
            "annual_cost": 28800,
            "users": 8,
            "utilization_pct": 65,
            "integrations": ["Salesforce", "Gmail"],
            "satisfaction_score": 7,
            "data_flows": [
                {"direction": "inbound", "connected_tool": "Salesforce", "data_type": "contacts", "automation_level": "basic"},
            ],
        },
        {
            "name": "ZoomInfo",
            "category": "enrichment",
            "vendor": "ZoomInfo",
            "monthly_cost": 2800,
            "annual_cost": 33600,
            "users": 5,
            "utilization_pct": 35,
            "integrations": ["Salesforce"],
            "satisfaction_score": 5,
            "data_flows": [
                {"direction": "outbound", "connected_tool": "Salesforce", "data_type": "enrichment", "automation_level": "manual"},
            ],
        },
        {
            "name": "Gong",
            "category": "conversation_intelligence",
            "vendor": "Gong",
            "monthly_cost": 2200,
            "annual_cost": 26400,
            "users": 12,
            "utilization_pct": 45,
            "integrations": ["Salesforce", "Zoom"],
            "satisfaction_score": 7,
            "data_flows": [
                {"direction": "outbound", "connected_tool": "Salesforce", "data_type": "call_insights", "automation_level": "basic"},
            ],
        },
        {
            "name": "Slack",
            "category": "other",
            "vendor": "Salesforce",
            "monthly_cost": 1200,
            "annual_cost": 14400,
            "users": 85,
            "utilization_pct": 95,
            "integrations": ["Salesforce", "Google Workspace"],
            "satisfaction_score": 9,
            "data_flows": [],
        },
        {
            "name": "Google Analytics",
            "category": "analytics",
            "vendor": "Google",
            "monthly_cost": 0,
            "annual_cost": 0,
            "users": 5,
            "utilization_pct": 30,
            "integrations": [],
            "satisfaction_score": 5,
            "data_flows": [],
        },
        {
            "name": "Notion",
            "category": "other",
            "vendor": "Notion",
            "monthly_cost": 800,
            "annual_cost": 9600,
            "users": 85,
            "utilization_pct": 80,
            "integrations": [],
            "satisfaction_score": 8,
            "data_flows": [],
        },
        {
            "name": "Mixpanel",
            "category": "analytics",
            "vendor": "Mixpanel",
            "monthly_cost": 1500,
            "annual_cost": 18000,
            "users": 10,
            "utilization_pct": 50,
            "integrations": [],
            "satisfaction_score": 6,
            "data_flows": [],
        },
        {
            "name": "Stripe",
            "category": "billing",
            "vendor": "Stripe",
            "monthly_cost": 0,
            "annual_cost": 0,
            "users": 3,
            "utilization_pct": 90,
            "integrations": ["Salesforce"],
            "satisfaction_score": 8,
            "data_flows": [
                {"direction": "outbound", "connected_tool": "Salesforce", "data_type": "payments", "automation_level": "basic"},
            ],
        },
    ],
    "gaps_identified": [
        "No intent data platform (missing buying signals)",
        "No AI SDR/prospecting automation",
        "Weak CRM-to-marketing data sync (manual processes)",
        "No product usage → CRM integration (PLG signals lost)",
        "No predictive lead scoring",
        "Missing customer health scoring for retention",
    ],
    "integration_quality": "basic",
}
